language: go

go:
  - 1.8.x
  - 1.9.x

go_import_path: nevill.io/gore

install:
  - go get -d -v -t ./... && go build -v ./...

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
